  actual_db: Local
  
  Local: 
    hostname: localhost
    port: 3306
    user: ana
    pass: ana
    database: enolaphp-tutorial
    driverbd: mysql
    persistent: FALSE
    charset: utf8
    
  Servidor: 
    hostname: localhost
    port: 3306
    user: user
    pass: pass
    database: db
    driverbd: mysql
    persistent: FALSE
    charset: utf8
