  session-profile: user_logged
  actual-authorization: Local
  
  Local:
    authorization-type: file
    modules:
      front: 
        - {url: /*, method: *}

    profiles:
      default: 
        permit:
          - front
        deny: {}
        error-redirect: /login
  
  Servidor:
    authorization-type: database
    connection: Authorization
    tables:
      user: user
      user-profile: user_profile
      profile: profile
      profile-permit: profile_permit
      profile-deny: profile_deny
      module: module
      key: modulekey