  base_url: http://localhost/enolaphp/
  index_page: 
  environment: development
  calculate_performance: true
  
  controllers: 
    index: 
      class: Index
      url: /
      
  filters: 
    authorization: 
      class: Authorization
      filtered: /*
  filters_after_processing: {}
  
  i18n: 
    default: en
    locales: es,fr,me
    
  url-components: enola-components
  session-profile: user_logged 
  components: {}
      
  libraries:
    validation: 
      path: Validation
      
  composer: 
      
  dependency_injection:
    - dependencyInjection