  url_app: http://localhost
  relative_url: /enolaphp
  index_page:
  environment: development
  calculate_performance: true
  session_autostart: false
  authorization_file: authorization
  
  controllers: 
    /: 
      class: Index
      
  filters: 
    authorization: 
      class: Authorization
      filtered: /*
  filters_after_processing: {}
  
  i18n: 
    default: en
    locales: es,fr,me
    
  url-components: enola-components  
  components: {}
      
  libraries:
    validation: 
      path: Validation/ValidationFields
      
  composer: 
      
  dependency_injection:
    - dependencyInjection